FROM ubuntu:25.04@sha256:5487c53773e2a8576213d1a2e18148fe167fabecfe7844724792f63041190d9d

RUN apt update \
    && \
    DEBIAN_FRONTEND="noninteractive" TZ="America/New_York" \
    apt install -y \
        qemu-user \
        libc6-arm64-cross \
        iptables \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

## All of this is from pwn-chal base image:
RUN  mkdir -p /app/
WORKDIR /app
RUN useradd ctf

# Setting up challenge stuff
COPY utilities/arm64/flag.txt /app/flag.txt
COPY utilities/arm64/chal /app/chal
COPY utilities/arm64/ynetd /opt/ynetd
COPY utilities/arm64/socat /opt/socat
COPY utilities/block-outbound.sh /etc/block-outbound.sh
RUN chmod +x /opt/*

# Setting up log stuff
RUN touch /var/log/chal.log
RUN chown -R root:ctf /var/log/chal.log
RUN chmod 740 /var/log/chal.log

# Other measures
RUN chmod o-rwx / 2>/dev/null

# QEMU-Specific ENVs for ARM/ARM64 distinction:
ENV LIBRARY_PATH="/usr/aarch64-linux-gnu"
ENV EMULATOR="qemu-aarch64"

COPY docker-entrypoint-arm.sh /docker-entrypoint.sh
CMD ["/docker-entrypoint.sh"]