FROM ubuntu:20.04@sha256:80ef4a44043dec4490506e6cc4289eeda2d106a70148b74b5ae91ee670e9c35d

# Really helpful blog: https://leimao.github.io/blog/Docker-Wine/
ARG DEBIAN_FRONTEND=noninteractive
ENV LANGUAGE en_US.UTF-8
RUN dpkg --add-architecture i386 \
    && apt-get update \
    && apt-get install -y --install-recommends wine64 xvfb xpra \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# The rest of this is similar to others:
# Setting up challenges stuff
RUN  mkdir -p /app/
WORKDIR /app
RUN useradd ctf-player

COPY utilities/flag.txt /app/flag.txt
COPY utilities/chal.exe /app/chal.exe
COPY utilities/ynetd /opt/ynetd
COPY utilities/socat /opt/socat
RUN chmod +x /opt/*

# Setting up log stuff
RUN touch /var/log/chal.log
RUN chown -R root:ctf-player /var/log/chal.log
RUN chmod 740 /var/log/chal.log

# Other measures
RUN chmod o-rwx / 2>/dev/null
RUN chmod 750 /app && chmod +x /app/chal.exe

ENV CHAL_NAME="chal.exe"
COPY utilities/wine.reg /opt/wine.req
COPY docker-entrypoint.sh /docker-entrypoint.sh
CMD ["/docker-entrypoint.sh", "IS_WINDOWS"]
