FROM ubuntu:20.04@sha256:80ef4a44043dec4490506e6cc4289eeda2d106a70148b74b5ae91ee670e9c35d

# Really helpful blog: https://leimao.github.io/blog/Docker-Wine/

ARG DEBIAN_FRONTEND=noninteractive
ENV LANGUAGE en_US.UTF-8

RUN dpkg --add-architecture i386 \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        wget ca-certificates software-properties-common \
    && mkdir -pm755 /etc/apt/keyrings \
    && wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key \
    && wget -nc -P /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/$(lsb_release -sc)/winehq-$(lsb_release -sc).sources \
    && apt-get update -y \
    && apt-get install -y --install-recommends winehq-staging \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get -y update \
    && apt-get install -y xvfb

# The rest of this is similar to others:
# Setting up challenges stuff
RUN  mkdir -p /app/
WORKDIR /app
RUN adduser --disabled-password ctf-player

COPY utilities/flag.txt /app/flag.txt
COPY utilities/chal /app/chal.exe
COPY utilities/ynetd /opt/ynetd
COPY utilities/socat /opt/socat
RUN chmod +x /opt/*

# Setting up log stuff
RUN touch /var/log/chal.log
RUN chown -R root:ctf-player /var/log/chal.log
RUN chmod 740 /var/log/chal.log

# Other measures
RUN chmod o-rwx / 2>/dev/null
RUN chmod 750 /app && chmod +x /app/chal.exe

ENV CHAL_NAME="chal.exe"

COPY docker-entrypoint.sh /docker-entrypoint.sh
CMD ["/docker-entrypoint.sh", "IS_WINDOWS"]