FROM python:3.10-slim-bullseye@sha256:f1fb49e4d5501ac93d0ca519fb7ee6250842245aba8612926a46a0832a1ed089

RUN  mkdir -p /app/
WORKDIR /app
RUN useradd ctf

# Downloading iptables
RUN apt update && TZ=ASIA/KARACHI \
	apt install -y iptables && \
	apt clean -y && \
	apt autoclean -y && \
	rm -rf /var/lib/apt/lists/*

# Setting up challenge stuff
COPY utilities/flag.txt /app/flag.txt
COPY utilities/chal /app/chal
COPY utilities/ynetd /opt/ynetd
COPY utilities/socat /opt/socat
COPY utilities/block-outbound.sh /etc/block-outbound.sh
COPY utilities/readflag /readflag
RUN chmod +x /opt/*

# Setting up log stuff
RUN touch /var/log/chal.log
RUN chown -R root:ctf /var/log/chal.log
RUN chmod 740 /var/log/chal.log

# Other measures
RUN chmod o-rwx / 2>/dev/null
RUN chmod 750 /app && chmod +x /app/chal

COPY docker-entrypoint.sh /docker-entrypoint.sh
CMD ["/docker-entrypoint.sh", "IS_PY"]