FROM ubuntu:24.04@sha256:2e863c44b718727c860746568e1d54afd13b2fa71b160f5cd9058fc436217b30

RUN apt update \
    && \
    DEBIAN_FRONTEND="noninteractive" TZ="America/New_York" \
    apt install -y \
        qemu-user \
        binutils-arm-linux-gnueabihf \
        libc6-armhf-cross \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

## All of this is from pwn-chal base image:
RUN  mkdir -p /app/
WORKDIR /app
RUN useradd ctf-player

# Setting up challenge stuff
COPY utilities/arm/flag.txt /app/flag.txt
COPY utilities/arm/chal /app/chal
COPY utilities/arm/ynetd /opt/ynetd
COPY utilities/arm/socat /opt/socat
RUN chmod +x /opt/*

# Setting up log stuff
RUN touch /var/log/chal.log
RUN chown -R root:ctf-player /var/log/chal.log
RUN chmod 740 /var/log/chal.log

# Other measures
RUN chmod o-rwx / 2>/dev/null

# QEMU-Specific ENVs for ARM/ARM64 distinction:
ENV LIBRARY_PATH="/usr/arm-linux-gnueabihf"
ENV EMULATOR="qemu-arm"

COPY docker-entrypoint-arm.sh /docker-entrypoint.sh
CMD ["/docker-entrypoint.sh"]
