name: Build & Push Docker Images

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [latest, kernel, 2504, 2410, 2404, 2304, 2204, 2004, 1804, 1604, cpp, python, python3, py313, py312, py311, p310, py39, py38, seccomp, x86, x86-cpp, crypto, sagemath, arm, arm64, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.tag }}
        run: |
          make ${{ matrix.tag }}
          docker push theflash2k/pwn-chal:${{ matrix.tag }}